<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '有效',
    'Are you sure you want to delete this item?' => '确定要删除该项目吗?',
    'Create' => '创建',
    'Delete' => '删除',
    'ID' => 'ID',
    'Key' => 'Key',
    'Reset' => '重置',
    'Search' => '搜索',
    'Section' => '分组',
    'Kvstore' => '键值存储',
    'Value' => '值',
    'Description' => '描述',
    'CreatedAt' => '创建时间',
    'UpdatedAt' => '更新时间',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" 已经存在于该分组中.',
    'Successfully saved kvstore on {section}'=>'{section} 保存成功'
];
